
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from prettytable import PrettyTable
var7 = PrettyTable()
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import random
kkkk=Tk()
def max1(x) :
    l=""
    c=x.count(x[0])
    l=x[0]
    for i in x :
        k=0
        for j in x :
            if i==j :
                k+=1
        if k>=c :
            c=k
            l=j
    return l
def se(x1,x3,y1=1) :
    x2=x1.copy()
    y2=0
    while y2<y1 :
        try :
            x4=x2.index(x3)
            x2.pop(x4)
        except :
            x2=max(x1)
            global c
            c=x2
        y2+=1
    return x4
k="phy"
k="chem"
m="elective"
y="phy"
x="Eng"
u="cs"
class11={1:[],2:[],3:[],4:[],5:[],6:[]}
for j in range(1,7):
    for i in range(6) :
        class11[j].append(None)
o=[k,y,u,x,m]
for p in range(1,7):
    j=0
    while j<6:
        r=random.randint(0,4)
        class11[p][j]=o[r]
        j+=1
    if k not in class11[p] or y not in class11[p] or m not in class11[p] or u not in class11[p] or x not in class11[p]:
        q=1
        while k not in class11[p] :
            q=1
            go=0
            a=0
            while go<6 :
                if class11[p][go]==None :
                    class11[p][go]=k
                    a+=1
                    break
                go+=1
            if a>0 :
                break
            c=max1(class11[p])
            g=se(class11[p],c,q)
            class11[p][g]=k
        while y not in class11[p] :
            q=1
            go=0
            a=0
            while go<6 :
                if class11[p][go]==None :
                    class11[p][go]=y
                    a+=1
                    break
                go+=1
            if a>0 :
                break
            c=max1(class11[p])
            g=se(class11[p],c,q)
            class11[p][g]=y
        while u not in class11[p] :
            q=1
            go=0
            a=0
            while go<6 :
                if class11[p][go]==None :
                    class11[p][go]=u
                    a+=1
                    break
                go+=1
            if a>0 :
                break
            c=max1(class11[p])
            g=se(class11[p],c,q)
            class11[p][g]=u
        while m not in class11[p] :
            q=1
            go=0
            a=0
            while go<6 :
                if class11[p][go]==None  :
                    class11[p][go]=k
                    a+=1
                    break
                go+=1
            if a>0 :
                break
            c=max1(class11[p])
            g=se(class11[p],c,q)
            class11[p][g]=m
        while x not in class11[p] :
            q=1
            go=0
            a=0
            while go<6 :
                if class11[p][go]==None :
                    class11[p][go]=x
                    a+=1
                    break
                go+=1
            if a>0 :
                break
            c=max1(class11[p])
            g=se(class11[p],c,q)
            class11[p][g]=x
var7.field_names = ['day',"5 to 7", "7 to 8", "4 to 5", "5 to 6",'break','6:30 to 7','8 to 9']
var7.add_row(["mon", class11[1][0], class11[1][1], class11[1][2], class11[1][3],'break', class11[1][4], class11[1][5]])
var7.add_row(["tue", class11[2][0], class11[2][1], class11[2][2], class11[2][3],'break',  class11[2][4], class11[2][5]])
var7.add_row(["wed",class11[3][0], class11[3][1], class11[3][2], class11[3][3],'break',  class11[3][4], class11[3][5]])
var7.add_row(["thurs",class11[4][0], class11[4][1], class11[4][2], class11[4][3],'break',  class11[4][4], class11[4][5]])
var7.add_row(["fri",class11[5][0], class11[5][1], class11[5][2], class11[5][3],'break',  class11[5][4], class11[5][5]])
var7.add_row(["sat",class11[6][0], class11[6][1], class11[6][2], class11[6][3],'break',  class11[6][5], class11[6][5]])
l1=tkinter.Label(text=var7)
l1.place(relx=0.5,rely=0.5)
kkkk.mainloop()
print(var7)
