
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\sys67\Desktop\build_timetable\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("865x631")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 631,
    width = 865,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    326.0758361816406,
    87.47190856933594,
    anchor="nw",
    text="Time Table",
    fill="#000000",
    font=("Poppins Regular", 38 * -1)
)

canvas.create_rectangle(
    4.55859375,
    237.1460723876953,
    862.9741821289062,
    636.8983917236328,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    28.05279541015625,
    341.2920837402344,
    anchor="nw",
    text="MON",
    fill="#000000",
    font=("Poppins Regular", 18 * -1)
)

canvas.create_text(
    36.468658447265625,
    395.9949951171875,
    anchor="nw",
    text="TUE",
    fill="#000000",
    font=("Poppins Regular", 18 * -1)
)

canvas.create_text(
    30.15673828125,
    447.5420227050781,
    anchor="nw",
    text="WED",
    fill="#000000",
    font=("Poppins Regular", 18 * -1)
)

canvas.create_text(
    32.260711669921875,
    499.08905029296875,
    anchor="nw",
    text="THU",
    fill="#000000",
    font=("Poppins Regular", 18 * -1)
)

canvas.create_text(
    39.62457275390625,
    551.6880493164062,
    anchor="nw",
    text="FRI",
    fill="#000000",
    font=("Poppins Regular", 18 * -1)
)

canvas.create_text(
    36.468658447265625,
    596.9231567382812,
    anchor="nw",
    text="SAT",
    fill="#000000",
    font=("Poppins Regular", 18 * -1)
)


canvas.create_rectangle(
    88.54158353805542,
    236.4447512626648,
    93.801513671875,
    636.3724060058594,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    214.77925443649292,
    233.9901156425476,
    220.03916931152344,
    636.8983917236328,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    337.8606219291687,
    236.09408903121948,
    343.1207275390625,
    636.8983612060547,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    459.71519231796265,
    236.4447512626648,
    465.32562255859375,
    631.9891662597656,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    649.7400698661804,
    233.9901156425476,
    655.0003662109375,
    634.0931549072266,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    760.7400698661804,
    240.1108889579773,
    766.0,
    645.1231079101562,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -5.259899616241455,
    233.9901156425476,
    862.6234741210938,
    239.25001525878906,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -0.3506894111633301,
    320.2524905204773,
    462.5204162597656,
    325.51239013671875,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    539.6656374931335,
    318.1485171318054,
    857.363525390625,
    323.4084167480469,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -0.07321357727050781,
    320.3325786590576,
    462.5204162597656,
    325.5893249511719,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    539.6656374931335,
    318.1485171318054,
    857.363525390625,
    323.4084167480469,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -0.3506894111633301,
    372.8514895439148,
    462.5204162597656,
    378.11138916015625,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    539.6656374931335,
    370.7474856376648,
    857.363525390625,
    376.00738525390625,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -0.07321357727050781,
    372.900053024292,
    462.5204162597656,
    378.15679931640625,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    539.6656374931335,
    370.7474856376648,
    857.363525390625,
    376.00738525390625,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -0.07321357727050781,
    426.5188274383545,
    462.5204162597656,
    431.77557373046875,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    539.6656374931335,
    424.3984866142273,
    857.363525390625,
    429.65838623046875,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -0.07321357727050781,
    480.13769340515137,
    462.5204162597656,
    485.3944396972656,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    539.6656374931335,
    478.04942655563354,
    857.363525390625,
    483.309326171875,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -0.3506894111633301,
    526.4405398368835,
    462.5204162597656,
    531.700439453125,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    539.6656374931335,
    524.3365969657898,
    857.363525390625,
    529.5964965820312,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -0.07321357727050781,
    526.3970012664795,
    462.5204162597656,
    531.6537475585938,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    539.6656374931335,
    524.3365969657898,
    857.363525390625,
    529.5964965820312,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -0.3506894111633301,
    576.935534954071,
    462.5204162597656,
    582.1954345703125,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    539.6656374931335,
    574.8315920829773,
    857.363525390625,
    580.0914916992188,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -0.07321357727050781,
    576.8617839813232,
    462.5204162597656,
    582.1185302734375,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    539.6656374931335,
    574.8315920829773,
    857.363525390625,
    580.0914916992188,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    538.6137118339539,
    233.9901156425476,
    543.8737182617188,
    637.2490997314453,
    fill="#000000",
    outline="")

canvas.create_text(
    476.546875,
    445.4380798339844,
    anchor="nw",
    text="BREAK",
    fill="#000000",
    font=("Poppins Regular", 18 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    158.0,
    351.87078857421875,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=113.0,
    y=334.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    158.0,
    404.87078857421875,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=113.0,
    y=387.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    158.0,
    404.87078857421875,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=113.0,
    y=387.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    158.0,
    455.87078857421875,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=113.0,
    y=438.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    158.0,
    510.87078857421875,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=113.0,
    y=493.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    158.0,
    558.8707885742188,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=113.0,
    y=541.3707885742188,
    width=90.0,
    height=33.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    158.0,
    613.8707885742188,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=113.0,
    y=596.3707885742188,
    width=90.0,
    height=33.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    282.0,
    351.87078857421875,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=237.0,
    y=334.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    282.0,
    404.87078857421875,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=237.0,
    y=387.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    282.0,
    455.87078857421875,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_10.place(
    x=237.0,
    y=438.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_11 = PhotoImage(
    file=relative_to_assets("entry_11.png"))
entry_bg_11 = canvas.create_image(
    282.0,
    510.87078857421875,
    image=entry_image_11
)
entry_11 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_11.place(
    x=237.0,
    y=493.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_12 = PhotoImage(
    file=relative_to_assets("entry_12.png"))
entry_bg_12 = canvas.create_image(
    282.0,
    558.8707885742188,
    image=entry_image_12
)
entry_12 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_12.place(
    x=237.0,
    y=541.3707885742188,
    width=90.0,
    height=33.0
)

entry_image_13 = PhotoImage(
    file=relative_to_assets("entry_13.png"))
entry_bg_13 = canvas.create_image(
    282.0,
    613.8707885742188,
    image=entry_image_13
)
entry_13 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_13.place(
    x=237.0,
    y=596.3707885742188,
    width=90.0,
    height=33.0
)

entry_image_14 = PhotoImage(
    file=relative_to_assets("entry_14.png"))
entry_bg_14 = canvas.create_image(
    404.0,
    351.87078857421875,
    image=entry_image_14
)
entry_14 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_14.place(
    x=359.0,
    y=334.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_15 = PhotoImage(
    file=relative_to_assets("entry_15.png"))
entry_bg_15 = canvas.create_image(
    404.0,
    404.87078857421875,
    image=entry_image_15
)
entry_15 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_15.place(
    x=359.0,
    y=387.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_16 = PhotoImage(
    file=relative_to_assets("entry_16.png"))
entry_bg_16 = canvas.create_image(
    404.0,
    455.87078857421875,
    image=entry_image_16
)
entry_16 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_16.place(
    x=359.0,
    y=438.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_17 = PhotoImage(
    file=relative_to_assets("entry_17.png"))
entry_bg_17 = canvas.create_image(
    404.0,
    510.87078857421875,
    image=entry_image_17
)
entry_17 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_17.place(
    x=359.0,
    y=493.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_18 = PhotoImage(
    file=relative_to_assets("entry_18.png"))
entry_bg_18 = canvas.create_image(
    404.0,
    558.8707885742188,
    image=entry_image_18
)
entry_18 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_18.place(
    x=359.0,
    y=541.3707885742188,
    width=90.0,
    height=33.0
)

entry_image_19 = PhotoImage(
    file=relative_to_assets("entry_19.png"))
entry_bg_19 = canvas.create_image(
    404.0,
    613.8707885742188,
    image=entry_image_19
)
entry_19 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_19.place(
    x=359.0,
    y=596.3707885742188,
    width=90.0,
    height=33.0
)

entry_image_20 = PhotoImage(
    file=relative_to_assets("entry_20.png"))
entry_bg_20 = canvas.create_image(
    603.0,
    346.87078857421875,
    image=entry_image_20
)
entry_20 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_20.place(
    x=558.0,
    y=329.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_21 = PhotoImage(
    file=relative_to_assets("entry_21.png"))
entry_bg_21 = canvas.create_image(
    600.0,
    407.87078857421875,
    image=entry_image_21
)
entry_21 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_21.place(
    x=555.0,
    y=390.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_22 = PhotoImage(
    file=relative_to_assets("entry_22.png"))
entry_bg_22 = canvas.create_image(
    603.0,
    399.87078857421875,
    image=entry_image_22
)
entry_22 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_22.place(
    x=558.0,
    y=382.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_23 = PhotoImage(
    file=relative_to_assets("entry_23.png"))
entry_bg_23 = canvas.create_image(
    603.0,
    450.87078857421875,
    image=entry_image_23
)
entry_23 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_23.place(
    x=558.0,
    y=433.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_24 = PhotoImage(
    file=relative_to_assets("entry_24.png"))
entry_bg_24 = canvas.create_image(
    603.0,
    505.87078857421875,
    image=entry_image_24
)
entry_24 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_24.place(
    x=558.0,
    y=488.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_25 = PhotoImage(
    file=relative_to_assets("entry_25.png"))
entry_bg_25 = canvas.create_image(
    603.0,
    553.8707885742188,
    image=entry_image_25
)
entry_25 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_25.place(
    x=558.0,
    y=536.3707885742188,
    width=90.0,
    height=33.0
)

entry_image_26 = PhotoImage(
    file=relative_to_assets("entry_26.png"))
entry_bg_26 = canvas.create_image(
    603.0,
    608.8707885742188,
    image=entry_image_26
)
entry_26 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_26.place(
    x=558.0,
    y=591.3707885742188,
    width=90.0,
    height=33.0
)

entry_image_27 = PhotoImage(
    file=relative_to_assets("entry_27.png"))
entry_bg_27 = canvas.create_image(
    714.0,
    346.87078857421875,
    image=entry_image_27
)
entry_27 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_27.place(
    x=669.0,
    y=329.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_28 = PhotoImage(
    file=relative_to_assets("entry_28.png"))
entry_bg_28 = canvas.create_image(
    714.0,
    399.87078857421875,
    image=entry_image_28
)
entry_28 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_28.place(
    x=669.0,
    y=382.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_29 = PhotoImage(
    file=relative_to_assets("entry_29.png"))
entry_bg_29 = canvas.create_image(
    714.0,
    450.87078857421875,
    image=entry_image_29
)
entry_29 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_29.place(
    x=669.0,
    y=433.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_30 = PhotoImage(
    file=relative_to_assets("entry_30.png"))
entry_bg_30 = canvas.create_image(
    714.0,
    505.87078857421875,
    image=entry_image_30
)
entry_30 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_30.place(
    x=669.0,
    y=488.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_31 = PhotoImage(
    file=relative_to_assets("entry_31.png"))
entry_bg_31 = canvas.create_image(
    714.0,
    552.8707885742188,
    image=entry_image_31
)
entry_31 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_31.place(
    x=669.0,
    y=535.3707885742188,
    width=90.0,
    height=33.0
)

entry_image_32 = PhotoImage(
    file=relative_to_assets("entry_32.png"))
entry_bg_32 = canvas.create_image(
    714.0,
    608.8707885742188,
    image=entry_image_32
)
entry_32 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_32.place(
    x=669.0,
    y=591.3707885742188,
    width=90.0,
    height=33.0
)

entry_image_33 = PhotoImage(
    file=relative_to_assets("entry_33.png"))
entry_bg_33 = canvas.create_image(
    818.0,
    346.87078857421875,
    image=entry_image_33
)
entry_33 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_33.place(
    x=773.0,
    y=329.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_34 = PhotoImage(
    file=relative_to_assets("entry_34.png"))
entry_bg_34 = canvas.create_image(
    158.0,
    286.87078857421875,
    image=entry_image_34
)
entry_34 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_34.place(
    x=113.0,
    y=269.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_35 = PhotoImage(
    file=relative_to_assets("entry_35.png"))
entry_bg_35 = canvas.create_image(
    282.0,
    286.87078857421875,
    image=entry_image_35
)
entry_35 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_35.place(
    x=237.0,
    y=269.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_36 = PhotoImage(
    file=relative_to_assets("entry_36.png"))
entry_bg_36 = canvas.create_image(
    404.0,
    286.87078857421875,
    image=entry_image_36
)
entry_36 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_36.place(
    x=359.0,
    y=269.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_37 = PhotoImage(
    file=relative_to_assets("entry_37.png"))
entry_bg_37 = canvas.create_image(
    603.0,
    281.87078857421875,
    image=entry_image_37
)
entry_37 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_37.place(
    x=558.0,
    y=264.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_38 = PhotoImage(
    file=relative_to_assets("entry_38.png"))
entry_bg_38 = canvas.create_image(
    714.0,
    281.87078857421875,
    image=entry_image_38
)
entry_38 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_38.place(
    x=669.0,
    y=264.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_39 = PhotoImage(
    file=relative_to_assets("entry_39.png"))
entry_bg_39 = canvas.create_image(
    818.0,
    281.87078857421875,
    image=entry_image_39
)
entry_39 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_39.place(
    x=773.0,
    y=264.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_40 = PhotoImage(
    file=relative_to_assets("entry_40.png"))
entry_bg_40 = canvas.create_image(
    818.0,
    399.87078857421875,
    image=entry_image_40
)
entry_40 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_40.place(
    x=773.0,
    y=382.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_41 = PhotoImage(
    file=relative_to_assets("entry_41.png"))
entry_bg_41 = canvas.create_image(
    818.0,
    450.87078857421875,
    image=entry_image_41
)
entry_41 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_41.place(
    x=773.0,
    y=433.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_42 = PhotoImage(
    file=relative_to_assets("entry_42.png"))
entry_bg_42 = canvas.create_image(
    818.0,
    505.87078857421875,
    image=entry_image_42
)
entry_42 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_42.place(
    x=773.0,
    y=488.37078857421875,
    width=90.0,
    height=33.0
)

entry_image_43 = PhotoImage(
    file=relative_to_assets("entry_43.png"))
entry_bg_43 = canvas.create_image(
    818.0,
    553.8707885742188,
    image=entry_image_43
)
entry_43 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_43.place(
    x=773.0,
    y=536.3707885742188,
    width=90.0,
    height=33.0
)

entry_image_44 = PhotoImage(
    file=relative_to_assets("entry_44.png"))
entry_bg_44 = canvas.create_image(
    818.0,
    608.8707885742188,
    image=entry_image_44
)
entry_44 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_44.place(
    x=773.0,
    y=591.3707885742188,
    width=90.0,
    height=33.0
)
import random
def max1(x) :
    l=""
    c=x.count(x[0])
    l=x[0]
    for i in x :
        k=0
        for j in x :
            if i==j :
                k+=1
        if k>=c :
            c=k
            l=j
    return l
def se(x1,x3,y1=1) :
    x2=x1.copy()
    y2=0
    while y2<y1 :
        try :
            x4=x2.index(x3)
            x2.pop(x4)
        except :
            x2=max(x1)
            global c
            c=x2
        y2+=1
    return x4
k="phy"
k="chem"
m="elective"
y="phy"
x="Eng"
u="cs"
class11={1:[],2:[],3:[],4:[],5:[],6:[]}
for j in range(1,7):
    for i in range(6) :
        class11[j].append(None)
o=[k,y,u,x,m]
for p in range(1,7):
    j=0
    while j<6:
        r=random.randint(0,4)
        class11[p][j]=o[r]
        j+=1
    if k not in class11[p] or y not in class11[p] or m not in class11[p] or u not in class11[p] or x not in class11[p]:
        q=1
        while k not in class11[p] :
            q=1
            go=0
            a=0
            while go<6 :
                if class11[p][go]==None :
                    class11[p][go]=k
                    a+=1
                    break
                go+=1
            if a>0 :
                break
            c=max1(class11[p])
            g=se(class11[p],c,q)
            class11[p][g]=k
        while y not in class11[p] :
            q=1
            go=0
            a=0
            while go<6 :
                if class11[p][go]==None :
                    class11[p][go]=y
                    a+=1
                    break
                go+=1
            if a>0 :
                break
            c=max1(class11[p])
            g=se(class11[p],c,q)
            class11[p][g]=y
        while u not in class11[p] :
            q=1
            go=0
            a=0
            while go<6 :
                if class11[p][go]==None :
                    class11[p][go]=u
                    a+=1
                    break
                go+=1
            if a>0 :
                break
            c=max1(class11[p])
            g=se(class11[p],c,q)
            class11[p][g]=u
        while m not in class11[p] :
            q=1
            go=0
            a=0
            while go<6 :
                if class11[p][go]==None  :
                    class11[p][go]=k
                    a+=1
                    break
                go+=1
            if a>0 :
                break
            c=max1(class11[p])
            g=se(class11[p],c,q)
            class11[p][g]=m
        while x not in class11[p] :
            q=1
            go=0
            a=0
            while go<6 :
                if class11[p][go]==None :
                    class11[p][go]=x
                    a+=1
                    break
                go+=1
            if a>0 :
                break
            c=max1(class11[p])
            g=se(class11[p],c,q)
            class11[p][g]=x
entry_1.insert(tkinter.INSERT,class11[1][0])
entry_8.insert(tkinter.INSERT,class11[1][1])
entry_14.insert(tkinter.INSERT,class11[1][2])
entry_20.insert(tkinter.INSERT,class11[1][3])
entry_27.insert(tkinter.INSERT,class11[1][4])
entry_33.insert(tkinter.INSERT,class11[1][5])
entry_4.insert(tkinter.INSERT,class11[2][0])
entry_9.insert(tkinter.INSERT,class11[2][1])
entry_15.insert(tkinter.INSERT,class11[2][2])
entry_22.insert(tkinter.INSERT,class11[2][3])
entry_28.insert(tkinter.INSERT,class11[2][4])
entry_40.insert(tkinter.INSERT,class11[2][5])
entry_3.insert(tkinter.INSERT,class11[3][0])
entry_10.insert(tkinter.INSERT,class11[3][1])
entry_16.insert(tkinter.INSERT,class11[3][2])
entry_23.insert(tkinter.INSERT,class11[3][3])
entry_29.insert(tkinter.INSERT,class11[3][4])
entry_41.insert(tkinter.INSERT,class11[3][5])
entry_5.insert(tkinter.INSERT,class11[3][0])
entry_11.insert(tkinter.INSERT,class11[3][1])
entry_17.insert(tkinter.INSERT,class11[3][2])
entry_24.insert(tkinter.INSERT,class11[3][3])
entry_30.insert(tkinter.INSERT,class11[3][4])
entry_42.insert(tkinter.INSERT,class11[3][5])
entry_6.insert(tkinter.INSERT,class11[4][0])
entry_12.insert(tkinter.INSERT,class11[4][1])
entry_18.insert(tkinter.INSERT,class11[4][2])
entry_25.insert(tkinter.INSERT,class11[4][3])
entry_31.insert(tkinter.INSERT,class11[4][4])
entry_43.insert(tkinter.INSERT,class11[4][5])
entry_7.insert(tkinter.INSERT,class11[5][0])
entry_13.insert(tkinter.INSERT,class11[5][1])
entry_19.insert(tkinter.INSERT,class11[5][2])
entry_26.insert(tkinter.INSERT,class11[5][3])
entry_32.insert(tkinter.INSERT,class11[5][4])
entry_44.insert(tkinter.INSERT,class11[5][5])
window.resizable(False,False)
window.mainloop()
