import matplotlib.pyplot as plt
import tkinter as tk
from tkinter import scrolledtext,ttk,messagebox
import numpy as np
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
root=tk.Tk()
root.title("Graph Your Grades")
root.geometry("500x500")
root.config(bg='#ffffb7')
l=[]
n=[]
m=[]
q=[]
e=[]
r=[]

def on_enter(event):
        nextexambut.config(bg='#BFBFFF')

def on_leave(event):
        nextexambut.config(bg='white')

def on_enter2(event):
        genbut.config(bg='#BFBFFF')

def on_leave2(event):
        genbut.config(bg='white')

def next():
       if combo.get().isalnum() and len(combo.get())!=0:
          l.append(combo.get())
          combo.delete(0, tk.END)
          n.append(quant_ent.get())
          m.append(quant_ent2.get())
          q.append(quant_ent3.get())
          e.append(quant_ent4.get())
          r.append(quant_ent5.get())
       else:
          messagebox.showwarning("Invalid!!","give valid exam name")
def on_select(event):
    selected_value.set(combo.get())
def kk() :
    # This file was generated by the Tkinter Designer by Parth Jadhav
    # https://github.com/ParthJadhav/Tkinter-Designer

    from prettytable import PrettyTable
    var7 = PrettyTable()
    from pathlib import Path
    import tkinter
    from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
    import random
    kkkk = tkinter.Toplevel()

    def max1(x):
        l = ""
        c = x.count(x[0])
        l = x[0]
        for i in x:
            k = 0
            for j in x:
                if i == j:
                    k += 1
            if k >= c:
                c = k
                l = j
        return l

    def se(x1, x3, y1=1):
        x2 = x1.copy()
        y2 = 0
        while y2 < y1:
            try:
                x4 = x2.index(x3)
                x2.pop(x4)
            except:
                x2 = max(x1)
                global c
                c = x2
            y2 += 1
        return x4

    k = "phy"
    k = "chem"
    m = "math"
    y = "phy"
    x = "Eng"
    u = "elective"
    class11 = {1: [], 2: [], 3: [], 4: [], 5: [], 6: []}
    for j in range(1, 7):
        for i in range(6):
            class11[j].append(None)
    o = [k, y, u, x, m]
    for p in range(1, 7):
        j = 0
        while j < 6:
            r = random.randint(0, 4)
            class11[p][j] = o[r]
            j += 1
        if k not in class11[p] or y not in class11[p] or m not in class11[p] or u not in class11[p] or x not in class11[
            p]:
            q = 1
            while k not in class11[p]:
                q = 1
                go = 0
                a = 0
                while go < 6:
                    if class11[p][go] == None:
                        class11[p][go] = k
                        a += 1
                        break
                    go += 1
                if a > 0:
                    break
                c = max1(class11[p])
                g = se(class11[p], c, q)
                class11[p][g] = k
            while y not in class11[p]:
                q = 1
                go = 0
                a = 0
                while go < 6:
                    if class11[p][go] == None:
                        class11[p][go] = y
                        a += 1
                        break
                    go += 1
                if a > 0:
                    break
                c = max1(class11[p])
                g = se(class11[p], c, q)
                class11[p][g] = y
            while u not in class11[p]:
                q = 1
                go = 0
                a = 0
                while go < 6:
                    if class11[p][go] == None:
                        class11[p][go] = u
                        a += 1
                        break
                    go += 1
                if a > 0:
                    break
                c = max1(class11[p])
                g = se(class11[p], c, q)
                class11[p][g] = u
            while m not in class11[p]:
                q = 1
                go = 0
                a = 0
                while go < 6:
                    if class11[p][go] == None:
                        class11[p][go] = k
                        a += 1
                        break
                    go += 1
                if a > 0:
                    break
                c = max1(class11[p])
                g = se(class11[p], c, q)
                class11[p][g] = m
            while x not in class11[p]:
                q = 1
                go = 0
                a = 0
                while go < 6:
                    if class11[p][go] == None:
                        class11[p][go] = x
                        a += 1
                        break
                    go += 1
                if a > 0:
                    break
                c = max1(class11[p])
                g = se(class11[p], c, q)
                class11[p][g] = x
    var7.field_names = ['day', "5 to 7", "7 to 8", "4 to 5", "5 to 6", 'break', '6:30 to 7', '8 to 9']
    var7.add_row(
        ["mon", class11[1][0], class11[1][1], class11[1][2], class11[1][3], 'break', class11[1][4], class11[1][5]])
    var7.add_row(
        ["tue", class11[2][0], class11[2][1], class11[2][2], class11[2][3], 'break', class11[2][4], class11[2][5]])
    var7.add_row(
        ["wed", class11[3][0], class11[3][1], class11[3][2], class11[3][3], 'break', class11[3][4], class11[3][5]])
    var7.add_row(
        ["thurs", class11[4][0], class11[4][1], class11[4][2], class11[4][3], 'break', class11[4][4], class11[4][5]])
    var7.add_row(
        ["fri", class11[5][0], class11[5][1], class11[5][2], class11[5][3], 'break', class11[5][4], class11[5][5]])
    var7.add_row(
        ["sat", class11[6][0], class11[6][1], class11[6][2], class11[6][3], 'break', class11[6][5], class11[6][5]])
    l1 = tkinter.Label(kkkk,text=var7,font=("Calibri",30))
    l1.pack()
    kkkk.mainloop()

def gen():
      global tt
      font1 = {'family': 'serif', 'color': 'blue', 'size': 20}
      font2 = {'family': 'serif', 'color': 'darkred', 'size': 15}
      plt.title("Mark Analysis", fontdict=font1)
      xpoints = np.array(n)
      ypoints = np.array(l)
      plt.xlabel("Exams", fontdict=font2)
      plt.plot(ypoints, xpoints, 'o-r')
      plt.ylabel('Marks', fontdict=font2)

      x2points = np.array(m)
      plt.plot(ypoints, x2points, 'o-b')

      x3points = np.array(q)
      plt.plot(ypoints, x3points, 'o-g')
      x4=np.array(e)
      x5=np.array(r)
      plt.plot(ypoints,x4,'o-y')
      plt.plot(ypoints,x5,'o-c')
      plt.legend(['maths', 'physics', 'chemistry','english','maths'])
      plt.show()
      total=tk.Label(root,text='AVERAGE',bg='#ffffb7',bd=2,font=('times',13,'bold'))
      total.place(x=50,y=290)
      a1=tk.Label(root,text=f"Average in maths : {round(sum(n)/len(n),2)}",font=('times',13),bg='#ffffb7')
      a1.place(x=15,y=320)
      a2=tk.Label(root,text=f"Average in physics : {round(sum(m)/len(m),2)}",font=('times',13),bg='#ffffb7')
      a2.place(x=15,y=350)
      a3=tk.Label(root,text=f"Average in chem : {round(sum(q)/len(q),2)}",font=('times',13),bg='#ffffb7')
      a3.place(x=15,y=380)
      a4=tk.Label(root,text=f"Average in english : {round(sum(e)/len(e),2)}",font=('times',13),bg='#ffffb7')
      a4.place(x=15,y=410)
      a5=tk.Label(root,text=f"Average in elective : {round(sum(r)/len(r),2)}",font=('times',13),bg='#ffffb7')
      a5.place(x=15,y=440)
      a6=scrolledtext.ScrolledText(root,bg='#ffffb7',font=('times',13),bd=0,borderwidth=0)
      a6.place(y=315,x=280)
      total=tk.Label(root,text='TOTAL',bg='#ffffb7',bd=2,font=('times',13,'bold'))
      total.place(x=300,y=290)
      for i in range(len(n)) :
          var1=n[i]+m[i]+q[i]+e[i]+r[i]
          a6.insert(tk.INSERT,f'Total in {l[i]}={var1}/500\n')
          print(l[i],var1)
      tt=tk.Button(root,text="TIME TABLE",relief='ridge',bd=2,font=('times'),command=kk)
      tt.place(x=370,y=450)
exam=tk.Label(root,text="EXAM NAME",font=('times',13),bg='#ffffb7',borderwidth=1)
exam.place(x=15,y=15)
maths=tk.Label(root,text='MATHS',font=('times',13),bg='#ffffb7')
maths.place(x=50,y=60)
phy=tk.Label(root,text='PHYSICS',font=('times',13),bg='#ffffb7')
phy.place(x=208,y=60)
che=tk.Label(root,text='CHEMISTRY',font=('times',13),bg='#ffffb7')
che.place(x=352,y=60)
en=tk.Label(root,text='ENGLISH',font=('times',13),bg='#ffffb7')
en.place(x=105,y=135)
ele=tk.Label(root,text='ELECTIVE',font=('times',13),bg='#ffffb7')
ele.place(x=272,y=135)
var=10
var2=11
var3=12
var4=13
var5=14
entry = ttk.Entry(root,width= 7,textvariable=var)
entry.place(x=20,y=120)
entry2 = ttk.Entry(root,width= 7,textvariable=var2)
entry2.place(x=180,y=120)
entry3 = ttk.Entry(root,width= 7,textvariable=var3)
entry3.place(x=340,y=120)
entry4 = ttk.Entry(root,width= 7,textvariable=var4)
entry4.place(x=80,y=196)
entry5 = ttk.Entry(root,width= 7,textvariable=var5)
entry5.place(x=249,y=196)
quant_ent=tk.Scale(root,from_=1,to=100,variable=var,orient='horizontal',bg='#BFBFFF',width=10,length=123,troughcolor='#FFD9AB')
quant_ent.place(x=18,y=85)

quant_ent2=tk.Scale(root,from_=1,to=100,variable=var2,orient='horizontal',bg='#BFBFFF',width=10,length=123,troughcolor='#FFD9AB')
quant_ent2.place(x=178,y=85)

quant_ent3=tk.Scale(root,from_=1,to=100,variable=var3,orient='horizontal',bg='#BFBFFF',width=10,length=123,troughcolor='#FFD9AB')
quant_ent3.place(x=338,y=85)

quant_ent4=tk.Scale(root,from_=1,to=100,variable=var4,orient='horizontal',bg='#BFBFFF',width=10,length=123,troughcolor='#FFD9AB')
quant_ent4.place(x=78,y=160)

quant_ent5=tk.Scale(root,from_=1,to=100,orient='horizontal',variable=var5,bg='#BFBFFF',width=10,length=123,troughcolor='#FFD9AB')
quant_ent5.place(x=248,y=160)

nextexambut=tk.Button(root,text="SAVE EXAM",relief='ridge',bd=2,font=('times'),command=next)
nextexambut.place(x=10,y=250)
genbut=tk.Button(root,text="ANALYSIS",relief='ridge',bd=2,font=('times'),command=gen)
genbut.place(x=340,y=250)
nextexambut.bind('<Enter>', on_enter)
nextexambut.bind('<Leave>', on_leave)
genbut.bind('<Enter>', on_enter2)
genbut.bind('<Leave>', on_leave2)
selected_value = tk.StringVar()

# Create a Combobox
combo = ttk.Combobox(root, textvariable=selected_value)
combo['values'] = ("Quarterly", "HalfYearly", "Midterm","Annual","RevisionTest")
combo.place(x=125,y=17)
combo.bind("<<ComboboxSelected>>", on_select)
combo.set("Select an option")
root.mainloop()
